repoURL: ""
targetRevision: main

django:
  imageRepository: ""
  dbHost: ""
  dbPort: "5432"
  rdsSecretArn: ""
  djangoSecretArn: ""

repositories:
  - name: final-project

applications:
  - name: django-app
    path: charts/django-app
    namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
