grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: 5Gi
  defaultDashboardsEnabled: true

prometheus:
  prometheusSpec:
    retention: 10d
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true
