replicaCount: 2

image:
  repository: ""
  tag: "dc6894b"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
  DB_NAME: "django_app"
  DB_HOST: ""
  DB_PORT: "5432"

externalSecrets:
  refreshInterval: 1h
  rdsSecretArn: ""
  djangoSecretArn: ""

livenessProbe:
  path: /healthz/
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  path: /readyz/
  initialDelaySeconds: 5
  periodSeconds: 10
