apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Chart.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ required "externalSecrets.rdsSecretArn is required" .Values.externalSecrets.rdsSecretArn | quote }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ required "externalSecrets.rdsSecretArn is required" .Values.externalSecrets.rdsSecretArn | quote }}
        property: password
    - secretKey: SECRET_KEY
      remoteRef:
        key: {{ required "externalSecrets.djangoSecretArn is required" .Values.externalSecrets.djangoSecretArn | quote }}
        property: secret_key
