apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | default "django_admin" | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | default "changeme" | quote }}
  SECRET_KEY: {{ .Values.secrets.djangoSecretKey | default "changeme" | quote }}
