{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ $.Values.targetRevision }}
    path: {{ .path }}
    {{- if eq .name "django-app" }}
    helm:
      parameters:
        - name: image.repository
          value: {{ $.Values.django.imageRepository | quote }}
        - name: env.DB_HOST
          value: {{ $.Values.django.dbHost | quote }}
        - name: env.DB_PORT
          value: {{ $.Values.django.dbPort | quote }}
        - name: externalSecrets.rdsSecretArn
          value: {{ $.Values.django.rdsSecretArn | quote }}
        - name: externalSecrets.djangoSecretArn
          value: {{ $.Values.django.djangoSecretArn | quote }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    {{- toYaml .syncPolicy | nindent 4 }}
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
