apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: {{ required "secretArn is required" .Values.secretArn | quote }}
        property: username
    - secretKey: admin-password
      remoteRef:
        key: {{ required "secretArn is required" .Values.secretArn | quote }}
        property: password
